import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const formatPeso = (n) => `PHP ${Number(n || 0).toLocaleString()}`;

export const downloadStructuredPdf = ({
  filename,
  title,
  subtitle,
  meta = [],
  sections = [],
  brand = 'ZwitBlakTea',
  footerText,
  titleAlign = 'left',
  subtitleAlign = 'left'
}) => {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  autoTable(doc, { body: [] });

  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 40;
  let y = 44;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  const titleText = String(title || 'Report');
  if (titleAlign === 'center') {
    doc.text(titleText, pageWidth / 2, y, { align: 'center' });
  } else {
    doc.text(titleText, marginX, y);
  }
  const brandText = String(brand || '').trim();
  if (brandText) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(brandText, pageWidth - marginX, y, { align: 'right' });
  }
  doc.setTextColor(15, 23, 42);
  y += 18;

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139);
    const subtitleText = String(subtitle);
    if (subtitleAlign === 'center') {
      doc.text(subtitleText, pageWidth / 2, y, { align: 'center' });
    } else {
      doc.text(subtitleText, marginX, y);
    }
    doc.setTextColor(15, 23, 42);
    y += 14;
  }

  if (meta.length > 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    for (const line of meta) {
      doc.text(`- ${String(line)}`, marginX, y);
      y += 12;
    }
    doc.setTextColor(15, 23, 42);
    y += 6;
  }

  for (const section of sections) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    const sectionTitle = String(section.title || '').trim();
    if (sectionTitle) doc.text(String(sectionTitle), marginX, y);
    y += 10;

    const head = section.columns?.length ? [section.columns] : undefined;
    const body = section.rows || [];

    autoTable(doc, {
      startY: y,
      head,
      body,
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 10,
        textColor: [15, 23, 42],
        cellPadding: 6,
        lineColor: [226, 232, 240],
        lineWidth: 0.6
      },
      headStyles: {
        fontStyle: 'bold',
        textColor: [15, 23, 42],
        fillColor: [241, 245, 249],
        fontSize: 9
      },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: section.columnStyles || {},
      margin: { left: marginX, right: marginX }
    });

    y = (doc.lastAutoTable?.finalY || y) + 18;
    if (y > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage();
      y = 44;
    }
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  const resolvedFooter =
    footerText === undefined
      ? (brandText ? `Generated by ${brandText} POS` : 'Generated by POS')
      : footerText;
  if (resolvedFooter) {
    doc.text(String(resolvedFooter), marginX, doc.internal.pageSize.getHeight() - 24);
  }
  doc.setTextColor(15, 23, 42);

  const safe = String(filename || 'report').replaceAll(/[^\w-]+/g, '_');
  doc.save(`${safe}.pdf`);
};

export const pdfFormats = { formatPeso };
