export const escapeHtml = (value) => {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
};

export const openPrintPdf = ({ title, filename, bodyHtml }) => {
  const w = window.open('', '_blank', 'noopener,noreferrer');
  if (!w) return;

  const doc = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title || 'Report')}</title>
    <style>
      @page { size: A4; margin: 14mm; }
      html, body { height: 100%; }
      body { font-family: Arial, Helvetica, sans-serif; color: #0f172a; }
      h1,h2,h3 { margin: 0; }
      .muted { color: #64748b; }
      .small { font-size: 12px; }
      .xs { font-size: 10px; }
      .row { display: flex; justify-content: space-between; gap: 12px; }
      .card { border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px; }
      .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }
      .pill { display: inline-block; border: 1px solid #e2e8f0; border-radius: 999px; padding: 4px 10px; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: .04em; color: #334155; }
      table { width: 100%; border-collapse: collapse; }
      th, td { border-bottom: 1px solid #e2e8f0; padding: 8px 6px; text-align: left; vertical-align: top; }
      th { font-size: 10px; text-transform: uppercase; letter-spacing: .06em; color: #64748b; }
      td { font-size: 12px; }
      .right { text-align: right; }
      .section { margin-top: 14px; }
      .section-title { font-size: 12px; font-weight: 800; text-transform: uppercase; letter-spacing: .08em; color: #0f172a; margin-bottom: 8px; }
      .footer { margin-top: 14px; font-size: 10px; color: #94a3b8; }
      .no-print { display: none; }
    </style>
  </head>
  <body>
    ${bodyHtml || ''}
    <div class="footer">Generated by ZwitBlakTea POS</div>
    <script>
      (function () {
        const filename = ${JSON.stringify(filename || '')};
        if (filename) document.title = filename;
        setTimeout(function () { window.print(); }, 50);
      })();
    </script>
  </body>
</html>`;

  w.document.open();
  w.document.write(doc);
  w.document.close();
  w.focus();
};

