CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS public.categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL,
  category_id integer,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  stock integer DEFAULT 0 CHECK (stock >= 0),
  barcode character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);

CREATE TABLE IF NOT EXISTS public.ingredients (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL UNIQUE,
  category character varying NOT NULL DEFAULT 'General'::character varying,
  unit character varying NOT NULL DEFAULT 'pcs'::character varying,
  quantity numeric NOT NULL DEFAULT 0 CHECK (quantity >= 0::numeric),
  min_stock numeric NOT NULL DEFAULT 0 CHECK (min_stock >= 0::numeric),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.addons (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL UNIQUE,
  category character varying NOT NULL DEFAULT 'General'::character varying,
  price_per_unit numeric NOT NULL CHECK (price_per_unit >= 0::numeric),
  variable_quantity boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.product_sizes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer,
  name character varying NOT NULL,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_sizes_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);

CREATE TABLE IF NOT EXISTS public.product_size_ingredients (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_size_id integer,
  ingredient_id integer,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  CONSTRAINT product_size_ingredients_product_size_id_fkey FOREIGN KEY (product_size_id) REFERENCES public.product_sizes(id),
  CONSTRAINT product_size_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id)
);

CREATE TABLE IF NOT EXISTS public.product_ingredients (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer,
  ingredient_id integer,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  CONSTRAINT product_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id),
  CONSTRAINT product_ingredients_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);

CREATE TABLE IF NOT EXISTS public.product_addons (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer,
  addon_id integer,
  CONSTRAINT product_addons_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_addons_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES public.addons(id)
);

CREATE TABLE IF NOT EXISTS public.addon_ingredients (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addon_id integer,
  ingredient_id integer,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  CONSTRAINT addon_ingredients_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES public.addons(id),
  CONSTRAINT addon_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id)
);

CREATE TABLE IF NOT EXISTS public.accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  password text NOT NULL,
  role character varying DEFAULT 'cashier'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'cashier'::character varying]::text[])),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  account_id character varying NOT NULL UNIQUE CHECK (account_id::text ~~ 'ADM%'::text OR account_id::text ~~ 'CSH%'::text),
  CONSTRAINT accounts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sales (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id uuid,
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  payment_method character varying CHECK (payment_method::text = ANY (ARRAY['Cash'::character varying, 'GCash'::character varying]::text[])),
  reference_number character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  cash_received numeric,
  change_amount numeric,
  CONSTRAINT sales_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);

CREATE TABLE IF NOT EXISTS public.transactions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id integer,
  product_id integer,
  quantity integer NOT NULL CHECK (quantity > 0),
  price numeric NOT NULL CHECK (price >= 0::numeric),
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  product_size_id integer,
  size_name character varying,
  CONSTRAINT transactions_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id),
  CONSTRAINT transactions_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT transactions_product_size_fk FOREIGN KEY (product_size_id) REFERENCES public.product_sizes(id)
);

CREATE TABLE IF NOT EXISTS public.transaction_addons (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id integer,
  addon_id integer,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  CONSTRAINT transaction_addons_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT transaction_addons_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES public.addons(id)
);

CREATE TABLE IF NOT EXISTS public.inventory_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer,
  change integer NOT NULL,
  reason character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT inventory_logs_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);

CREATE TABLE IF NOT EXISTS public.ingredient_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id integer,
  change numeric NOT NULL,
  reason character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ingredient_logs_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id)
);

CREATE TABLE IF NOT EXISTS public.activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  actor_account_id text,
  actor_name text,
  action text NOT NULL,
  area text,
  entity_type text,
  entity_id text
);

ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addon_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingredient_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_size_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_sizes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'accounts') THEN
    CREATE POLICY "Allow all accounts" ON public.accounts FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'activity_logs') THEN
    CREATE POLICY "Allow all activity logs" ON public.activity_logs FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'addon_ingredients') THEN
    CREATE POLICY "Allow all addon ingredients" ON public.addon_ingredients FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'addons') THEN
    CREATE POLICY "Allow all addons" ON public.addons FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'categories') THEN
    CREATE POLICY "Allow all categories" ON public.categories FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ingredient_logs') THEN
    CREATE POLICY "Allow all ingredient logs" ON public.ingredient_logs FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ingredients') THEN
    CREATE POLICY "Allow all ingredients" ON public.ingredients FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'inventory_logs') THEN
    CREATE POLICY "Allow all inventory logs" ON public.inventory_logs FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'product_addons') THEN
    CREATE POLICY "Allow all product addons" ON public.product_addons FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'product_ingredients') THEN
    CREATE POLICY "Allow all product ingredients" ON public.product_ingredients FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'product_size_ingredients') THEN
    CREATE POLICY "Allow all product size ingredients" ON public.product_size_ingredients FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'product_sizes') THEN
    CREATE POLICY "Allow all product sizes" ON public.product_sizes FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'products') THEN
    CREATE POLICY "Allow all products" ON public.products FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sales') THEN
    CREATE POLICY "Allow all sales" ON public.sales FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'transaction_addons') THEN
    CREATE POLICY "Allow all transaction addons" ON public.transaction_addons FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'transactions') THEN
    CREATE POLICY "Allow all transactions" ON public.transactions FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

ALTER TABLE public.ingredients ADD COLUMN IF NOT EXISTS category character varying;
UPDATE public.ingredients SET category = 'General' WHERE category IS NULL OR btrim(category) = '';
ALTER TABLE public.ingredients ALTER COLUMN category SET DEFAULT 'General'::character varying;
ALTER TABLE public.ingredients ALTER COLUMN category SET NOT NULL;

ALTER TABLE public.addons ADD COLUMN IF NOT EXISTS category character varying;
UPDATE public.addons SET category = 'General' WHERE category IS NULL OR btrim(category) = '';
ALTER TABLE public.addons ALTER COLUMN category SET DEFAULT 'General'::character varying;
ALTER TABLE public.addons ALTER COLUMN category SET NOT NULL;

ALTER TABLE public.accounts ADD COLUMN IF NOT EXISTS is_active boolean;
UPDATE public.accounts SET is_active = true WHERE is_active IS NULL;
ALTER TABLE public.accounts ALTER COLUMN is_active SET DEFAULT true;
ALTER TABLE public.accounts ALTER COLUMN is_active SET NOT NULL;

NOTIFY pgrst, 'reload schema';
